// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IncludeToolbox
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string MonikersGuidString = "41e64718-3ed1-4ace-aeb4-fbe550d81000";
        public static Guid MonikersGuid = new Guid(MonikersGuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int hash = 0x000C;
        public const int include13 = 0x0001;
        public const int include16 = 0x0002;
        public const int IncludeFormatterIcons_0 = 0x0003;
        public const int IncludeFormatterIcons_1 = 0x0004;
        public const int IncludeFormatterIcons_2 = 0x0005;
        public const int IncludeFormatterIcons_3 = 0x0006;
        public const int IncludeFormatterPackage = 0x0007;
        public const int IncludeGraphToolbarIcons_0 = 0x0008;
        public const int IncludeGraphToolbarIcons_1 = 0x0009;
        public const int IncludeFormatterIcons = 0x000A;
        public const int IncludeGraphToolbarIcons = 0x000B;
    }
}