// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IncludeToolbox
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string IncludeToolboxString = "2e77f2e4-5f04-4052-8e63-ca2b41cd0315";
        public static Guid IncludeToolbox = new Guid(IncludeToolboxString);

        public const string GHeaderOnlyString = "a34e853e-8679-4a07-918e-982a1b3b0a6b";
        public static Guid GHeaderOnly = new Guid(GHeaderOnlyString);

        public const string GOnlyVCString = "1175290a-3e8f-4718-868c-c08b5d2b09a7";
        public static Guid GOnlyVC = new Guid(GOnlyVCString);

        public const string GOnlyCppString = "bf397895-9307-431f-a823-1c85d430243a";
        public static Guid GOnlyCpp = new Guid(GOnlyCppString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ContextMenuGroup = 0x0001;
        public const int ItemContextGroup = 0x021A;
        public const int IncludeWhatYouUseId = 0x0100;
        public const int FormatIncludesId = 0x0101;
        public const int TrialAndError = 0x0102;
        public const int IWYUProjId = 0x0103;
        public const int ProjectWideTrialAndErrorRemoval = 0x0110;
    }
}