// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IncludeToolbox
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidIncludeToolboxPackageString = "5c2743c4-1b3f-4edd-b6a0-4379f867d47f";
        public static Guid guidIncludeToolboxPackage = new Guid(guidIncludeToolboxPackageString);

        public const string guidCodeMenuCmdSetString = "aef3a531-8af4-4b7b-800a-e32503dfc6e2";
        public static Guid guidCodeMenuCmdSet = new Guid(guidCodeMenuCmdSetString);

        public const string guidIncludeGraphWindowCmdSetString = "032eb795-1f1c-440d-af98-43cdc1de7a8b";
        public static Guid guidIncludeGraphWindowCmdSet = new Guid(guidIncludeGraphWindowCmdSetString);

        public const string guidProjectMenuCmdSetString = "1970ecf3-6c03-4ccf-b422-8dd07f774ed8";
        public static Guid guidProjectMenuCmdSet = new Guid(guidProjectMenuCmdSetString);

        public const string guidGraphWindowToolbarCmdSetString = "0b242452-870a-489b-8336-88fd01aef0c1";
        public static Guid guidGraphWindowToolbarCmdSet = new Guid(guidGraphWindowToolbarCmdSetString);

        public const string guidIconsGraphWindowToolbarString = "10311b90-33ad-4479-a326-4b40f7f7aca8";
        public static Guid guidIconsGraphWindowToolbar = new Guid(guidIconsGraphWindowToolbarString);

        public const string guidIconsCommonString = "dd14909e-b406-4cfa-b492-08b8127679df";
        public static Guid guidIconsCommon = new Guid(guidIconsCommonString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EditMenuGroup = 0x1020;
        public const int FormatIncludesId = 0x0100;
        public const int IncludeWhatYouUseId = 0x0103;
        public const int TrialAndErrorRemovalId = 0x0104;
        public const int IncludeGraphToolWindowGroup = 0x1000;
        public const int IncludeGraphToolWindowCommandId = 0x0102;
        public const int ProjectMenuGroup = 0x1000;
        public const int ProjectWideTrialAndErrorRemovalId = 0x0100;
        public const int idGraphWindowToolbar = 0x1000;
        public const int idGraphWindowToolbarGroupRefresh = 0x1001;
        public const int idGraphWindowToolbarGroupSaveGraph = 0x1002;
        public const int idGraphWindowRefresh = 0x0101;
        public const int idGraphWindowRefreshMode = 0x0102;
        public const int idGraphWindowRefreshModeOptions = 0x0103;
        public const int idGraphWindowSaveGraph = 0x0104;
        public const int iconRefresh = 0x0001;
        public const int iconSaveGraph = 0x0002;
        public const int iconFormatter = 0x0001;
        public const int iconIWYU = 0x0002;
        public const int iconTrialAndError = 0x0003;
        public const int iconExplorer = 0x0004;
    }
}