// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IncludeToolbox
{
    internal sealed partial class Vsix
    {
        public const string Id = "IncludeToolbox2019.1431faa5-aa04-47af-8289-9d887e0696a4";
        public const string Name = "Include Toolbox 2019";
        public const string Description = @"Various tools for managing C/C++ #includes: Formatting, sorting, exploring, pruning.";
        public const string Language = "en-US";
        public const string Version = "3.1.0";
        public const string Author = "Agrael";
        public const string Tags = "Include, IWYU, Include Formatting, Include Sorting, #include";
    }
}
